{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zadarma.pjsip",
    "module": "pjsiplib",
    "version": "1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pjsiplib-1.8.2.aar",
          "url": "pjsiplib-1.8.2.aar",
          "size": 16779977,
          "sha512": "6ea6fc39c95c9ca6f96ec76be668b6bb2a25851b836bd90bc591e71a6110c2229036985b2226fe178499df70d85d5ad7413d589947282d108163285586015488",
          "sha256": "a00edaa4977507afed26cff33975cf1ccb0697478344b0c44563f20890d5d7d7",
          "sha1": "35ec5b425b503a8c4747358d15ac684bcb97b5ba",
          "md5": "c030852d4d266742405c8b8f5ec09f22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "pjsiplib-1.8.2.aar",
          "url": "pjsiplib-1.8.2.aar",
          "size": 16779977,
          "sha512": "6ea6fc39c95c9ca6f96ec76be668b6bb2a25851b836bd90bc591e71a6110c2229036985b2226fe178499df70d85d5ad7413d589947282d108163285586015488",
          "sha256": "a00edaa4977507afed26cff33975cf1ccb0697478344b0c44563f20890d5d7d7",
          "sha1": "35ec5b425b503a8c4747358d15ac684bcb97b5ba",
          "md5": "c030852d4d266742405c8b8f5ec09f22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pjsiplib-1.8.2-sources.jar",
          "url": "pjsiplib-1.8.2-sources.jar",
          "size": 389144,
          "sha512": "34842f28ad482837f1e19d9ef2fae00d5b5454ab2f31a8c23cb01de7fe2120a368c51d0bbf2dff74ef8d92f85d631db6e75690b9a2681a31d2e83fa560719095",
          "sha256": "6963084375dd54aab4f9ad2496fdae2fcc24ca99ac61bf4212d22e8fda5da886",
          "sha1": "2d6a0997b4c65cda060a81b30a69ac7df632835a",
          "md5": "c6028d165099a3a148701b9f4a9188bf"
        }
      ]
    }
  ]
}
